// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import RequestingConcept from "./Requesting/RequestingConcept.ts";
import SummariesConcept from "./Scriblink/summariesConcept.ts";
import PasswordAuthConcept from "./Scriblink/passwordAuthConcept.ts";
import NotesConcept from "./Scriblink/notesConcept.ts";
import TagsConcept from "./Scriblink/tagsConcept.ts";
import FolderConcept from "./Scriblink/folderConcept.ts";
import RequestConcept from "./Scriblink/requestConcept.ts";

export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as SummariesConcept } from "./Scriblink/summariesConcept.ts";
export type { default as PasswordAuthConcept } from "./Scriblink/passwordAuthConcept.ts";
export type { default as NotesConcept } from "./Scriblink/notesConcept.ts";
export type { default as TagsConcept } from "./Scriblink/tagsConcept.ts";
export type { default as FolderConcept } from "./Scriblink/folderConcept.ts";
export type { default as RequestConcept } from "./Scriblink/requestConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const Summaries = Engine.instrumentConcept(new SummariesConcept(db));
export const PasswordAuth = Engine.instrumentConcept(new PasswordAuthConcept(db));
export const Notes = Engine.instrumentConcept(new NotesConcept(db));
export const Tags = Engine.instrumentConcept(new TagsConcept(db));
export const Folder = Engine.instrumentConcept(new FolderConcept(db));
export const Request = Engine.instrumentConcept(new RequestConcept(db));
