// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import RequestingConcept from "./Requesting/RequestingConcept.ts";

export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";

// Initialize the database connection
export const [db, client] = await testDb();

export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
